locale = "zh-SG"
label = "简体字"
weight = 2
title = "Dahi Open Tech"

[params]
  displayName = "简体"
  isoCode = "zh-SG"
  rtl = false
  dateFormat = "2006-01-02"
  description = "Welcome to Dahi Blog"

[author]
  name = "Dahi"
  image = "https://img3.tapimg.com/avatars/etag/FrXPfpRN0pwF5SuiQ7MIPO3BXdkK.png"
  headline = "ようこそ"
  bio = "Studying"
  links = [
    { github = "https://github.com/dahisea" }
  ]
